### ISSUE TITLE
Alternative installation option as Homebrew dropped support for Mac OS 10.15 

### ISSUE THREAD

**Issue by vinosamari** [render-oss/render-cli#52]
I use Mac OS Catalina (10.15) and i have been trying for days to install the render cli to no avail.

This is what the terminal output looks like 
```
$ brew tap render-oss/render && brew install render
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).

You have 25 outdated formulae and 1 outdated cask installed.
You can upgrade them with brew upgrade
or list them with brew outdated.

Warning: You are using macOS 10.15.
We (and Apple) do not provide support for this old version.
It is expected behaviour that some formulae will fail to build in this old version.
It is expected behaviour that Homebrew will be buggy and slow.
Do not create any issues about this on Homebrew's GitHub repositories.
Do not create any issues even if you think this message is unrelated.
Any opened issues will be immediately closed without response.
Do not ask for help from MacHomebrew on Twitter.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or may not accept it.

==> Fetching dependencies for render-oss/render/render: rust and deno
==> Fetching rust
==> Cloning https://github.com/rust-lang/cargo.git
Updating /Users/macbookpro/Library/Caches/Homebrew/rust--cargo--git
==> Checking out tag 0.68.0
HEAD is now at 8ecd4f20a known_hosts: Switch the documentation to stable.
HEAD is now at 8ecd4f20a known_hosts: Switch the documentation to stable.
==> Downloading https://static.rust-lang.org/dist/2023-01-10/cargo-1.66.1-x86_64-apple-darwin.tar.gz
Already downloaded: /Users/macbookpro/Library/Caches/Homebrew/downloads/22e16cc18a119241f1defa7167d901f1b56b6527a9f65ff1084c0beb8d82eb4c--cargo-1.66.1-x86_64-apple-darwin.tar.gz
==> Downloading https://static.rust-lang.org/dist/rustc-1.67.1-src.tar.gz
Already downloaded: /Users/macbookpro/Library/Caches/Homebrew/downloads/a6baffd4dcdd84525d18a324a9e616abf58e3113ec8185dc7c5b616080170244--rustc-1.67.1-src.tar.gz
==> Fetching deno
==> Downloading https://static.crates.io/crates/v8/v8-0.60.1.crate
Already downloaded: /Users/macbookpro/Library/Caches/Homebrew/downloads/2feda43f38fa77c6c374f4273db8653d4e5c366bdf1a2f6372b6fd24e6883136--v8-0.60.1.crate
==> Downloading https://github.com/denoland/v8/archive/05fb6e97fc6c5fdd2e79e4f9a51c5bf0ca0ef991.tar.gz
Already downloaded: /Users/macbookpro/Library/Caches/Homebrew/downloads/7c6c7d274ff990074c33f7aaa60fa179a21381399260f28ef008fefdc564646f--v8-05fb6e97fc6c5fdd2e79e4f9a51c5bf0ca0ef991.tar.gz
==> Cloning https://gn.googlesource.com/gn.git
Updating /Users/macbookpro/Library/Caches/Homebrew/deno--gn--git
==> Checking out revision bf4e17dc67b2a2007475415e3f9e1d1cf32f6e35
HEAD is now at bf4e17dc Revert recent performance-related  commits.
HEAD is now at bf4e17dc Revert recent performance-related  commits.
==> Downloading https://github.com/denoland/deno/releases/download/v1.30.3/deno_src.tar.gz
Already downloaded: /Users/macbookpro/Library/Caches/Homebrew/downloads/94a0bf23597720af014b989f210072fcf2146f68b9f71da4364c11d7cc2e7c5e--deno_src.tar.gz
==> Fetching render-oss/render/render
==> Cloning https://github.com/render-oss/render-cli.git
Updating /Users/macbookpro/Library/Caches/Homebrew/render--git
==> Checking out tag v0.1.5
HEAD is now at 7dc06e4 Ed/render blueprint from template (#51)
HEAD is now at 7dc06e4 Ed/render blueprint from template (#51)
==> Installing render from render-oss/render
==> Installing dependencies for render-oss/render/render: rust and deno
==> Installing render-oss/render/render dependency: rust
==> ./configure --prefix=/usr/local/Cellar/rust/1.67.1 --enable-vendor --set rust.jemalloc --release-channel=stable
==> make
Last 15 lines from /Users/macbookpro/Library/Logs/Homebrew/rust/02.make:
Traceback (most recent call last):
  File "/private/tmp/rust-20230215-73394-1y1a5ak/rustc-1.67.1-src/src/bootstrap/bootstrap.py", line 954, in <module>
    main()
  File "/private/tmp/rust-20230215-73394-1y1a5ak/rustc-1.67.1-src/src/bootstrap/bootstrap.py", line 937, in main
    bootstrap(help_triggered)
  File "/private/tmp/rust-20230215-73394-1y1a5ak/rustc-1.67.1-src/src/bootstrap/bootstrap.py", line 912, in bootstrap
    build.download_toolchain()
  File "/private/tmp/rust-20230215-73394-1y1a5ak/rustc-1.67.1-src/src/bootstrap/bootstrap.py", line 436, in download_toolchain
    self._download_component_helper(filename, "rustc", tarball_suffix)
  File "/private/tmp/rust-20230215-73394-1y1a5ak/rustc-1.67.1-src/src/bootstrap/bootstrap.py", line 465, in _download_component_helper
    get(
  File "/private/tmp/rust-20230215-73394-1y1a5ak/rustc-1.67.1-src/src/bootstrap/bootstrap.py", line 52, in get
    raise RuntimeError("failed verification")
RuntimeError: failed verification
make: *** [all] Error 1

Do not report this issue to Homebrew/brew or Homebrew/core!

These open issues may also help:
shadowsocks-rust : add service and config https://github.com/Homebrew/homebrew-core/pull/122828
cargo-*: do not depend on `rust` on runtime https://github.com/Homebrew/homebrew-core/pull/116786
```

At some point a package took over 800 minutes to install and it is just 1gb. 
![Screenshot 2023-02-15 at 2 57 39 PM](https://user-images.githubusercontent.com/60850993/219065282-e15c03f4-d3ee-46f8-a76d-869eb8969728.png)

As per this warning i only have this community to turn to for help/alternatives for installing the CLI on Mac OS 10.15
```
Warning: You are using macOS 10.15.
We (and Apple) do not provide support for this old version.
It is expected behaviour that some formulae will fail to build in this old version.
It is expected behaviour that Homebrew will be buggy and slow.
Do not create any issues about this on Homebrew's GitHub repositories.
Do not create any issues even if you think this message is unrelated.
Any opened issues will be immediately closed without response.
Do not ask for help from MacHomebrew on Twitter.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yours
elf and submit a fix as a pull request.
We will review it but may or may not accept it.
```

Thank you

**Comment by mdgale** [comment]
The [releases page](https://github.com/render-oss/render-cli/releases) has specific binaries you could try using.

You could also try [pulling the repo and running the app](https://github.com/render-oss/render-cli#the-moderately-difficult-way-pull-the-repo) from there. [The docs page](https://render.com/docs/cli#from-source-unsupported-operating-systems) has some additional tips for dealing with deno.

hth!

**Comment by vinosamari** [comment]
Thank you for your time @mdgale . Going through those options
