### ISSUE TITLE
Error installing render-cli using Homebrew on macOS M1

### ISSUE THREAD

**Issue by adisve** [render-oss/render-cli#55]
Looks like there is a hash mismatch in the lock file for the ajv-formats package. 

Running the commands `brew tap render-oss/render ; brew install render` in the terminal, the following output appears

```
==> Fetching render-oss/render/render
==> Cloning https://github.com/render-oss/render-cli.git
Updating /Users/adisveletanlic/Library/Caches/Homebrew/render--git
==> Checking out tag v0.1.5
HEAD is now at 7dc06e4 Ed/render blueprint from template (#51)
HEAD is now at 7dc06e4 Ed/render blueprint from template (#51)
==> Installing render from render-oss/render
==> make build-completions
Last 15 lines from /Users/adisveletanlic/Library/Logs/Homebrew/render/01.make:
Download https://deno.land/std@0.129.0/node/_core.ts
Download https://deno.land/std@0.129.0/node/_process/exiting.ts
Download https://deno.land/std@0.129.0/node/_fixed_queue.ts
Download https://deno.land/std@0.129.0/node/internal/buffer.mjs
Download https://deno.land/std@0.129.0/node/internal_binding/_utils.ts
Download https://deno.land/std@0.129.0/node/internal_binding/buffer.ts
Download https://deno.land/std@0.129.0/encoding/base64.ts
Download https://deno.land/std@0.129.0/encoding/base64url.ts
Download https://deno.land/std@0.129.0/node/internal_binding/string_decoder.ts
Download https://deno.land/std@0.129.0/node/internal_binding/_node.ts
error: The source code is invalid, as it does not match the expected hash in the lock file.
  Specifier: https://esm.sh/v86/ajv-formats@2.1.1
  Lock file: deps-lock.json
make[1]: *** [deps] Error 10
make: *** [build-local] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/render-oss/homebrew-render/issues

/opt/homebrew/Library/Homebrew/utils/github/api.rb:301:in `raise_error': GitHub API Error: Bad credentials (GitHub::API::AuthenticationFailedError)
The GitHub credentials in the macOS keychain may be invalid.
Clear them with:
  printf "protocol=https\nhost=github.com\n" | git credential-osxkeychain erase
Create a GitHub personal access token:
https://github.com/settings/tokens/new?scopes=gist,repo,workflow&description=Homebrew
echo 'export HOMEBREW_GITHUB_API_TOKEN=your_token_here' >> ~/.zshrc

	from /opt/homebrew/Library/Homebrew/utils/github/api.rb:241:in `open_rest'
	from /opt/homebrew/Library/Homebrew/utils/github.rb:180:in `search'
	from /opt/homebrew/Library/Homebrew/utils/github.rb:184:in `search_results_items'
	from /opt/homebrew/Library/Homebrew/utils/github.rb:38:in `search_issues'
	from /opt/homebrew/Library/Homebrew/utils/github.rb:64:in `issues_for_formula'
	from /opt/homebrew/Library/Homebrew/exceptions.rb:498:in `fetch_issues'
	from /opt/homebrew/Library/Homebrew/exceptions.rb:493:in `issues'
	from /opt/homebrew/Library/Homebrew/exceptions.rb:549:in `dump'
	from /opt/homebrew/Library/Homebrew/brew.rb:151:in `rescue in <main>'
	from /opt/homebrew/Library/Homebrew/brew.rb:139:in `<main>'
/opt/homebrew/Library/Homebrew/formula.rb:2551:in `block in system': Failed executing: make build-completions (BuildError)
	from /opt/homebrew/Library/Homebrew/formula.rb:2487:in `open'
	from /opt/homebrew/Library/Homebrew/formula.rb:2487:in `system'
	from /opt/homebrew/Library/Taps/render-oss/homebrew-render/Formula/render.rb:42:in `install'
	from /opt/homebrew/Library/Homebrew/build.rb:177:in `block (3 levels) in install'
	from /opt/homebrew/Library/Homebrew/extend/kernel.rb:500:in `with_env'
	from /opt/homebrew/Library/Homebrew/build.rb:139:in `block (2 levels) in install'
	from /opt/homebrew/Library/Homebrew/formula.rb:1327:in `block in brew'
	from /opt/homebrew/Library/Homebrew/formula.rb:2718:in `block (2 levels) in stage'
	from /opt/homebrew/Library/Homebrew/extend/kernel.rb:500:in `with_env'
	from /opt/homebrew/Library/Homebrew/formula.rb:2717:in `block in stage'
	from /opt/homebrew/Library/Homebrew/resource.rb:159:in `block (2 levels) in unpack'
	from /opt/homebrew/Library/Homebrew/download_strategy.rb:111:in `chdir'
	from /opt/homebrew/Library/Homebrew/download_strategy.rb:103:in `stage'
	from /opt/homebrew/Library/Homebrew/resource.rb:155:in `block in unpack'
	from /opt/homebrew/Library/Homebrew/mktemp.rb:77:in `block in run'
	from /opt/homebrew/Library/Homebrew/mktemp.rb:77:in `chdir'
	from /opt/homebrew/Library/Homebrew/mktemp.rb:77:in `run'
	from /opt/homebrew/Library/Homebrew/resource.rb:267:in `stage_resource'
	from /opt/homebrew/Library/Homebrew/resource.rb:154:in `unpack'
	from /opt/homebrew/Library/Homebrew/resource.rb:128:in `stage'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `stage'
	from /opt/homebrew/Library/Homebrew/formula.rb:2697:in `stage'
	from /opt/homebrew/Library/Homebrew/formula.rb:1320:in `brew'
	from /opt/homebrew/Library/Homebrew/build.rb:133:in `block in install'
	from /opt/homebrew/Library/Homebrew/extend/kernel.rb:500:in `with_env'
	from /opt/homebrew/Library/Homebrew/build.rb:128:in `install'
	from /opt/homebrew/Library/Homebrew/build.rb:229:in `<main>'
```

**Comment by lazyatom** [comment]
I am also seeing the first part of the error:

```
brew install render
==> Fetching render-oss/render/render
==> Cloning https://github.com/render-oss/render-cli.git
Updating /Users/james/Library/Caches/Homebrew/render--git
==> Checking out tag v0.1.5
HEAD is now at 7dc06e4 Ed/render blueprint from template (#51)
HEAD is now at 7dc06e4 Ed/render blueprint from template (#51)
==> Installing render from render-oss/render
==> make build-completions
Last 15 lines from /Users/james/Library/Logs/Homebrew/render/01.make:
Download https://deno.land/std@0.129.0/node/_core.ts
Download https://deno.land/std@0.129.0/node/_fixed_queue.ts
Download https://deno.land/std@0.129.0/node/_process/exiting.ts
Download https://deno.land/std@0.129.0/encoding/base64.ts
Download https://deno.land/std@0.129.0/encoding/base64url.ts
Download https://deno.land/std@0.129.0/node/internal/buffer.mjs
Download https://deno.land/std@0.129.0/node/internal_binding/_utils.ts
Download https://deno.land/std@0.129.0/node/internal_binding/buffer.ts
Download https://deno.land/std@0.129.0/node/internal_binding/_node.ts
Download https://deno.land/std@0.129.0/node/internal_binding/string_decoder.ts
error: The source code is invalid, as it does not match the expected hash in the lock file.
  Specifier: https://esm.sh/v86/ajv-formats@2.1.1
  Lock file: deps-lock.json
make[1]: *** [deps] Error 10
make: *** [build-local] Error 2
```

**Comment by BilalBudhani** [comment]
Facing the same issue 

```
➜ brew install render
==> Fetching dependencies for render-oss/render/render: deno
==> Fetching deno
==> Downloading https://ghcr.io/v2/homebrew/core/deno/manifests/1.33.2
########################################################################################################### 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/deno/blobs/sha256:29099ebbcec92f0755a4e1aff00037ec689b92f955b3efd
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:29099ebbcec92f0755a4e1aff0003
########################################################################################################### 100.0%
==> Fetching render-oss/render/render
==> Cloning https://github.com/render-oss/render-cli.git
Cloning into '/Users/bilal/Library/Caches/Homebrew/render--git'...
==> Checking out tag v0.1.5
HEAD is now at 7dc06e4 Ed/render blueprint from template (#51)
==> Installing render from render-oss/render
==> Installing dependencies for render-oss/render/render: deno
==> Installing render-oss/render/render dependency: deno
==> Pouring deno--1.33.2.arm64_ventura.bottle.tar.gz
🍺  /opt/homebrew/Cellar/deno/1.33.2: 10 files, 77.6MB
==> Installing render-oss/render/render
==> make build-completions
Last 15 lines from /Users/bilal/Library/Logs/Homebrew/render/01.make:
Download https://deno.land/std@0.129.0/node/_core.ts
Download https://deno.land/std@0.129.0/node/_process/exiting.ts
Download https://deno.land/std@0.129.0/node/_fixed_queue.ts
Download https://deno.land/std@0.129.0/node/internal/buffer.mjs
Download https://deno.land/std@0.129.0/node/internal_binding/_utils.ts
Download https://deno.land/std@0.129.0/node/internal_binding/buffer.ts
Download https://deno.land/std@0.129.0/encoding/base64.ts
Download https://deno.land/std@0.129.0/encoding/base64url.ts
Download https://deno.land/std@0.129.0/node/internal_binding/string_decoder.ts
Download https://deno.land/std@0.129.0/node/internal_binding/_node.ts
error: The source code is invalid, as it does not match the expected hash in the lock file.
  Specifier: https://esm.sh/v86/ajv-formats@2.1.1
  Lock file: deps-lock.json
make[1]: *** [deps] Error 10
make: *** [build-local] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/render-oss/homebrew-render/issues
```

**Comment by fmarkwong** [comment]
+1

**Comment by robdimarco-render** [comment]
https://github.com/render-oss/render-cli/pull/57
